apiVersion: v1
kind: ReplicationController
metadata:
  name: jmbx-in-qa-01.gen-3
spec:
  replicas: 2
  selector:
    app: jmbx-in
    env: qa-01
  template:
    metadata:
      labels:
        app: jmbx-in
        env: qa-01
      name: jmbx-in-qa-01
    spec:
      containers:
      - name: jmbx-in-qa-01
        image: docker.jimubox.com/qa-01/jmbx-in:latest
        livenessProbe:
          httpGet:
            path: /Status/Version
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 3
        resources:
          limits:
            cpu: 2.0
            memory: 2Gi
